Coordinare/Pages/Events/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Coordinare.Pages.Events
{
    public class CreateModel : PageModel
    {
        private IEventCatalog _eservice;
        private IRoomCatalog _rservice;
        private IUserCatalog _uservice;
        private ITagSelection _tservice;

        private Object _lock = new object();
        [BindProperty] public Event Event { get; set; }
        public string Time { get; set; }
        public List<TagName> Tags { get; set; }
        public List<Room> Rooms { get; set; }
        public List<User> Speakers { get; set; }

        [BindProperty]
        public TimeSpan dura { get; set; }
        public CreateModel(IEventCatalog eservice, IRoomCatalog rservice, IUserCatalog uservice, ITagSelection tservice)
        {
            _eservice = eservice;
            _rservice = rservice;
            _uservice = uservice;
            _tservice = tservice;
            Rooms = _rservice.GetAllRoomsAsync().Result;
            Speakers = uservice.GetAllUsersAsync().Result.FindAll(u => u.Speaker == true);
        }

        public void OnGet()
        {
            Tags = _tservice.GetTagNames().Result;
            Tags ??= new List<TagName>();
            Time = DateTime.Now.ToString("yyyy-MM-ddT00:00");
        }

        public async Task<IActionResult> OnPostAsync(int sid, List<int> tag)
        {

            Event place = new Event();
            Event.LastUpdated = DateTime.Now;
            Event.Speaker = _uservice.GetUserFromIdAsync(sid).Result;
            if (!ModelState.IsValid && Event.Speaker == null)
            {
                return Page();
            }

            if (_eservice.GetAllEvents().Result.Exists(e => !(e.Room_ID == Event.Room_ID && ((Event.DateTime.Add(Event.Duration) < e.DateTime) || (Event.DateTime > e.DateTime.Add(e.Duration))))))
            {
                lock (_lock)
                {
                    _eservice.CreateEvent(Event);
                    List<Event> el = _eservice.GetAllEvents().Result;
                    place = el.Last();
                }
                foreach (int item in tag)
                {
                    _tservice.CreateNewTagToEvent(place, _tservice.GetTagNameFromId(item).Result);
                }
            }
            return RedirectToPage("GetAllEvents");

        }

    }
}

Coordinare/Pages/Events/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace Coordinare.Pages.Events
{
    public class DeleteModel : PageModel
    {
        private IEventCatalog _service;
        private IUserCatalog _uservice;
        public Event Event { get; set; }
        public User Speaker { get; set; }
        public DeleteModel(IEventCatalog service, IUserCatalog uservice)
        {
            _service = service;
            _uservice = uservice;
        }
        public void OnGet(int id)
        {
          //  Func<int, bool> testbool = i => i == 0 ? true : false;
          Event = _service.GetEventFromId(id).Result;
          Speaker = _uservice.GetUserFromIdAsync(Event.Speaker.User_ID).Result;

        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            _service.DeleteEvent(id);
            return RedirectToPage("GetAllEvents");
        }
    }
}

Coordinare/Pages/Events/GetAllEvents.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Coordinare.Interfaces;
using Coordinare.Models;

namespace Coordinare.Pages.Events
{
    public class GetAllEventsModel : PageModel
    {
        private IEventCatalog _service;
        public List<Event> Events { get; set; }
        public GetAllEventsModel(IEventCatalog service)
        {
            _service = service;
        }
        public async void OnGet()
        {
            Events = _service.GetAllEvents().Result;
        }
    }
}

Coordinare/Pages/Events/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO.Enumeration;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Coordinare.Models;
using Coordinare.Pages.Users;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.WebEncoders.Testing;

namespace Coordinare.Pages.Events
{
    public class IndexModel : PageModel
    {
        private IEventCatalog _service;
        private IUserCatalog _usercatalog;
        public List<Event> Events { get; set; }
        [BindProperty]
        public string Filter { get; set; }
        [BindProperty]
        public string DateSort { get; set; }
        [BindProperty]
        public string NameSort { get; set; }
        [BindProperty]
        public string SeatSort { get; set; }
        public IndexModel(IEventCatalog service, IUserCatalog uservice)
        {
            _service = service;
            _usercatalog = uservice;
        }

        public void OnGet()
        {
            Events = _service.GetAllEvents().Result;
            Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
            Events.Sort((e1, e2) => e1.DateTime.CompareTo(e2.DateTime));
            DateSort ??= DateSort = "down";
            NameSort ??= NameSort = "down";
            SeatSort ??= SeatSort = "down";
        }

        public async Task<IActionResult> OnPostSearch(string filter, string option)
        {
            if (!string.IsNullOrEmpty(filter) && !string.IsNullOrEmpty(option))
            {
                if (option == "name")
                {
                    Filter = filter;
                    Events = _service.GetAllEvents().Result.FindAll(e => e.DateTime > DateTime.UtcNow).FindAll(e => e.EventName.ToLower().Contains(filter.ToLower()));
                    Events.Sort((e1, e2) => e1.EventName.CompareTo(e2.EventName));
                }
            }
            if (Events == null)
            {
                Events = _service.GetAllEvents().Result;
                Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostSortdate(string sort)
        {
            if (sort == "down")
            {
                if (!string.IsNullOrEmpty(Filter))
                {
                    Events = _service.GetAllEvents().Result.FindAll(e => e.DateTime > DateTime.UtcNow).FindAll(e => e.EventName.ToLower().Contains(Filter.ToLower()));
                }
                else
                {
                    Events = _service.GetAllEvents().Result;
                    Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
                }
                Events.Sort((e1, e2) => e2.DateTime.CompareTo(e1.DateTime));
                DateSort = "up";
                NameSort = "down";
                SeatSort = "down";
            }
            else
            {
                if (!string.IsNullOrEmpty(Filter))
                {
                    Events = _service.GetAllEvents().Result.FindAll(e => e.DateTime > DateTime.UtcNow).FindAll(e => e.EventName.ToLower().Contains(Filter.ToLower()));
                }
                else
                {
                    Events = _service.GetAllEvents().Result;
                    Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
                }
                Events.Sort((e1, e2) => e1.DateTime.CompareTo(e2.DateTime));
                DateSort = "down";
                NameSort = "down";
                SeatSort = "down";
            }

            return Page();
        }

        public async Task<IActionResult> OnPostSortname(string sort)
        {
            if (sort == "down")
            {
                if (!string.IsNullOrEmpty(Filter))
                {
                    Events = _service.GetAllEvents().Result.FindAll(e => e.DateTime > DateTime.UtcNow).FindAll(e => e.EventName.ToLower().Contains(Filter.ToLower()));
                }
                else
                {
                    Events = _service.GetAllEvents().Result;
                    Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
                }
                Events.Sort((e1, e2) => e2.EventName.CompareTo(e1.EventName));
                NameSort = "up";
                DateSort = "down";
                SeatSort = "down";
            }
            else
            {
                if (!string.IsNullOrEmpty(Filter))
                {
                    Events = _service.GetAllEvents().Result.FindAll(e => e.DateTime > DateTime.UtcNow).FindAll(e => e.EventName.ToLower().Contains(Filter.ToLower()));
                }
                else
                {
                    Events = _service.GetAllEvents().Result;
                    Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
                }
                Events.Sort((e1, e2) => e1.EventName.CompareTo(e2.EventName));
                NameSort = "down";
                DateSort = "down";
                SeatSort = "down";
            }
            return Page();
        }

        public async Task<IActionResult> OnPostSortseat(string sort)
        {
            if (sort == "down")
            {
                if (!string.IsNullOrEmpty(Filter))
                {
                    Events = _service.GetAllEvents().Result.FindAll(e => e.DateTime > DateTime.UtcNow).FindAll(e => e.EventName.ToLower().Contains(Filter.ToLower()));
                }
                else
                {
                    Events = _service.GetAllEvents().Result;
                    Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
                }
                Events.Sort((e1, e2) => e2.SS_amount.CompareTo(e1.SS_amount));
                NameSort = "down";
                DateSort = "down";
                SeatSort = "up";
            }
            else
            {
                if (!string.IsNullOrEmpty(Filter))
                {
                    Events = _service.GetAllEvents().Result.FindAll(e => e.DateTime > DateTime.UtcNow).FindAll(e => e.EventName.ToLower().Contains(Filter.ToLower()));
                }
                else
                {
                    Events = _service.GetAllEvents().Result;
                    Events = Events.FindAll(e => e.DateTime > DateTime.UtcNow);
                }
                Events.Sort((e1, e2) => e1.SS_amount.CompareTo(e2.SS_amount));
                NameSort = "down";
                DateSort = "down";
                SeatSort = "down";
            }

            return Page();
        }
    }
}

Coordinare/Pages/Events/Info.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Coordinare.Interfaces;
using Coordinare.Models;
using Coordinare.Services;

namespace Coordinare.Pages.Events
{
    public class InfoModel : PageModel
    {
        private IEventCatalog _service;
        private IBookingCatalog _Bservice;
        private ITagSelection _tservice;
        public LoginService _Lservice;
        private IRoomCatalog _Rservice;
        public List<Booking> UserBookings;
        public Event Event { get; set; }
        public User CurrentUser { get; set; }
        public List<Tag> Tags { get; set; }
        public int Seats { get; set; }
        public Room Room { get; set; }
        public List<Booking> Bookings { get; set; }

        [BindProperty] public int EventID { get; set; }

        public InfoModel(IEventCatalog service, IBookingCatalog Bservice, LoginService Lservice, ITagSelection tservice, IRoomCatalog RService)
        {
            _service = service;
            _Bservice = Bservice;
            _Lservice = Lservice;
            _tservice = tservice;
            _Rservice = RService;
        }
        public void OnGet(int id)
        {
          Event = _service.GetEventFromId(id).Result;
          EventID = id;
          CurrentUser = _Lservice.GetLoggedInUser();
          if (CurrentUser != null)
          { 
              UserBookings = _Bservice.GetBookingsFromUser(CurrentUser.User_ID).Result;
          }
          Tags = _tservice.GetAllTags().Result.FindAll(t => t.Event_ID == id);
          Seats = _Bservice.GetBookingsFromEvent(id).Result.Count;
          Room = _Rservice.GetRoomsFromIdAsync(Event.Room_ID).Result;
          Bookings = _Bservice.GetBookingsFromEvent(id).Result;
          Tags ??= new List<Tag>();
            //Tags ??= new List<Tag>() er det samme som if statement nedenunder.
            //if (Tags == null)
            //{
            //    Tags = new List<Tag>();
            //}
            Room ??= new Room();

        }

        public async Task<IActionResult> OnPost()
        {
            return RedirectToPage("/Bookings/CreateBooking", new { EventID = this.EventID });
        }

    }
}

Coordinare/Pages/Events/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Coordinare.Interfaces;
using Coordinare.Models;

namespace Coordinare.Pages.Events
{
    public class UpdateModel : PageModel
    {
        private IEventCatalog _service;
        private IRoomCatalog _rservice;
        private IUserCatalog _uservice;
        [BindProperty]
        public Event Event { get; set; }
        public List<Room> Rooms { get; set; }
        public List<User> Speakers { get; set; }
        public string Time { get; set; }
        public UpdateModel(IEventCatalog service, IRoomCatalog rservice, IUserCatalog uservice)
        {
            _service = service;
            _rservice = rservice;
            _uservice = uservice;
            Rooms = _rservice.GetAllRoomsAsync().Result;
            Speakers = uservice.GetAllUsersAsync().Result.FindAll(u => u.Speaker == true);
        }
        public async void OnGet(int id)
        {
          Event = await _service.GetEventFromId(id);
          Time = DateTime.Now.ToString("yyyy-MM-ddT00:00");
        }
        public async Task<IActionResult> OnPostAsync(int sid)
        {
            Event.Speaker = _uservice.GetUserFromIdAsync(sid).Result;
            Event.LastUpdated = DateTime.Now;
            if (!ModelState.IsValid && Event.Speaker == null)
            {
                return Page();
            }
            _service.UpdateEvent(Event, Event.Event_ID);
            return RedirectToPage("GetAllEvents");
            
        }
    }
}

Coordinare/Pages/Rooms/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Rooms
{
    public class DeleteModel : PageModel
    {
        private IRoomCatalog _service;
        [BindProperty] public Room Room { get; set; }
        public string TextBox { get; set; }

        public DeleteModel(IRoomCatalog service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            TextBox = "Are you sure that you want to delete?";
            Room = await _service.GetRoomsFromIdAsync(id);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        { 
            await _service.DeleteRoomAsync(Room.Room_ID);
            return RedirectToPage("GetAllRooms");
        }
    }
}

Coordinare/Pages/Rooms/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Exceptions;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Rooms
{
    public class UpdateModel : PageModel
    {

        private IRoomCatalog _service;
        [BindProperty] 
        public Room Room { get; set; }
        public string TextBox { get; set; }
        [BindProperty] 
        public string OldId { get; set; }
        //public List<Room> Rooms { get; set; }

        public UpdateModel(IRoomCatalog service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            OldId = id;
            TextBox = "Update a Room?";
            Room = await _service.GetRoomsFromIdAsync(id);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Room room)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            try
            {
                await _service.UpdateRoomAsync(Room, OldId);
            }
            catch (ExistsException e)
            {
                TextBox = $"Error! {e.Message}";
                return Page();
            }
            return RedirectToPage("GetAllRooms");
        }
    }
}

Coordinare/Pages/Events/Create.cshtml
@page
@using Coordinare.Models
@using Coordinare.Services
@model Coordinare.Pages.Events.CreateModel
@{
}
<form method="post">
    <div class="form-group">
        <label asp-for="Event.EventName" class="custom-control-label"></label>
        <input asp-for="@Model.Event.EventName" class="form-control" placeholder="Write Name..."/>
        <span class="field-validation-error text-danger" asp-validation-for="Event.EventName"></span>
    </div>
    <div class="form-group">
        <label asp-for="Event.DateTime" class="custom-control-label"></label>
        <input min="@Model.Time" type="datetime-local" asp-for="Event.DateTime" class="form-control" />
        <span class="field-validation-error text-danger" asp-validation-for="Event.DateTime"></span>
    </div>
    <div class="form-group">
        <label asp-for="Event.Speaker" class="custom-control-label"></label>
        <select name="sid">
            <option value="">Speaker is Needed</option>
            @foreach (User item in @Model.Speakers)
            {
                <option value="@item.User_ID">@item.Username</option>
            }
        </select>
        <span class="field-validation-error text-danger" asp-validation-for="Event.Speaker"></span>
    </div>
    <div class="form-group">
        <label asp-for="Event.Room_ID" class="custom-control-label"></label>
        <select asp-for="Event.Room_ID">
            <option value="">Choose Room Later</option>
            @foreach (Room item in @Model.Rooms)
            {
                <option value="@item.Room_ID">@item.Room_ID</option>
            }
        </select>
    </div>
    <div class="row">
        @foreach (TagName item in @Model.Tags)
        {
            <p>@item.Name:</p><input type="checkbox" value="@item.Tag_ID" name="tag"/>
        }
    </div>
    <div class="form-group">
        <label asp-for="Event.Eventinfo"></label>
        <textarea asp-for="Event.Eventinfo" placeholder="Write info of the event here..." cols="50"></textarea>
        <span class="field-validation-error text-danger" asp-validation-for="Event.Eventinfo"></span>
    </div>
    <div class="form-group">
        <label asp-for="Event.Duration"></label>
        <input value="00:00" type="time" asp-for="Event.Duration" />
        <span class="field-validation-error text-danger" asp-validation-for="Event.Duration"></span>
    </div>
    <div class="form-group">
        <label>Speaciel Seats</label>
        <input type="number" asp-for="Event.SS_amount" />
        <span class="field-validation-error text-danger" asp-validation-for="Event.SS_amount"></span>
    </div>
    <input type="submit" value="create" class="btn btn-primary" /> <a asp-page="Index">Back to Events</a>
</form>

Coordinare/Pages/Events/Delete.cshtml
@page
@model Coordinare.Pages.Events.DeleteModel
@{
}
<form method="post">
    <input type="hidden" asp-for="Event.Event_ID" name="id"> 
    <div class="form-group">
        <label asp-for="Event.Event_ID"></label>
        <h5>@Model.Event.Event_ID</h5>
    </div>
    <div class="form-group">
        <label asp-for="Event.EventName"></label>
        <h5>@Model.Event.EventName</h5>
    </div>
    @if (Model.Speaker != null)
    {
        <div class="form-group">
            <label asp-for="Speaker.Name"></label>
            <h5>@Model.Speaker.Name</h5>
        </div>
    }
    <div class="form-group">
        <label asp-for="Event.Room_ID"></label>
        <h5>@Model.Event.Room_ID</h5>
    </div>
    <div class="form-group">
        <label asp-for="Event.DateTime"></label>
        <h5>@Model.Event.DateTime</h5>
    </div>
    <div class="form-group">
        <label asp-for="Event.Duration"></label>
        <h5>@Model.Event.Duration</h5>
    </div>
    <div class="form-group">
        <label asp-for="Event.SS_amount"></label>
        <h5>@Model.Event.SS_amount</h5>
    </div>
    <input type="submit" value="Delete" class="btn btn-primary"/>
</form>

Coordinare/Pages/Events/Index.cshtml
@page
@using Coordinare.Models
@model Coordinare.Pages.Events.IndexModel
@{
}
<form method="post" asp-page-handler="search">
    <input asp-for="DateSort" type="hidden"/>
    <input name="option"/>
    <input type="text" name="filter" value="" placeholder="Search here..."/>
    <input type="submit" value="Search"/>
</form>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>
                Event ID
            </th>
            <th>
                Duration
            </th>
            <th>
                Speaker
            </th>
            <th>
                Room Id
            </th>
            <th>
                <form method="post" asp-page-handler="sortname">
                    <input type="hidden" asp-for="Filter" />
                    <input type="hidden" asp-for="DateSort" />
                    <input asp-for="SeatSort" type="hidden" />
                    <input asp-for="NameSort" type="hidden" name="sort" />
                    <button class="btn" style="border: none; background-color: inherit; cursor: pointer;">
                        Name
                        @if (@Model.NameSort == "down")
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z" />
                            </svg>
                        }
                        @if (@Model.NameSort == "up")
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z" />
                            </svg>
                        }
                    </button>
                </form>
            </th>
            <th>
                <form method="post" asp-page-handler="sortdate">
                    <input type="hidden" asp-for="Filter" />
                    <input type="hidden" asp-for="NameSort" />
                    <input asp-for="DateSort" type="hidden" name="sort" />
                    <input asp-for="SeatSort" type="hidden" />
                    <button class="btn" style="border: none; background-color: inherit; cursor: pointer;">
                        Date
                        @if (@Model.DateSort == "down")
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z" />
                            </svg>
                        }
                        @if (@Model.DateSort == "up")
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z" />
                            </svg>
                        }
                    </button>
                </form>
            </th>
            <th>
                Event info
            </th>
            <th>
                <form method="post" asp-page-handler="sortseat">
                    <input type="hidden" asp-for="Filter"/>
                    <input type="hidden" asp-for="NameSort"/>
                    <input type="hidden" asp-for="DateSort" />
                    <input asp-for="SeatSort" type="hidden" name="sort"/>
                    <button class="btn" style="border: none; background-color: inherit; cursor: pointer;">
                        Special seats
                        @if (@Model.SeatSort == "down")
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
                            </svg>
                        }
                        @if (@Model.SeatSort == "up")
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"/>
                            </svg>
                        }
                    </button>
                </form>
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Events)
        {
            <tr>
                <td>
                    @item.Event_ID
                </td>
                <td>
                    @item.Duration
                </td>
                <td>
                    @item.Speaker.Name
                </td>
                <td>
                    @item.Room_ID
                </td>
                <td>
                    @item.EventName
                </td>
                <td>
                    @item.DateTime
                </td>
                <td>
                    @item.Eventinfo
                </td>
                <td>
                    @item.SS_amount
                </td>
                <td><p><a asp-page="/Events/Info" asp-route-id="@item.Event_ID">See Details</a></p></td>
            </tr>
        }
</table>

Coordinare/Pages/Events/Info.cshtml
@page
@using Coordinare.Services
@using Coordinare.Models
@model Coordinare.Pages.Events.InfoModel
@{ int openseats = Model.Room.Capacity - Model.Bookings.Count;}
@{
}
<div class="row">
    <a asp-page="Index">Back</a>
</div>
<label>Tags:</label>
<div class="row">
    @foreach (Tag item in Model.Tags)
    {<div class="text-center" style="padding: 10px">
            <p>@item.TagName </p>
        </div>
    }
</div>
<div class="text-center">
    <h1>@Model.Event.EventName</h1>
    <p>@Model.Event.Eventinfo</p>
    <div class="row">
        <p>Attendees: @Model.Bookings.FindAll(b => b.InWaitingList == false).Count. OpenSeats: @openseats. People on Waiting list: @Model.Bookings.FindAll(b => b.InWaitingList == true).Count.</p>
        <form method="post">
            @if (Model._Lservice.GetLoggedInUser() != null)
            {
                <input type="hidden" asp-for="@Model.EventID"/>
                @if (Model.UserBookings.Exists(x => x.User_ID == Model.CurrentUser.User_ID && Model.UserBookings.Exists(y => y.Event_ID == Model.EventID)))
                {

                }
                else
                {
                    <input type="submit" value="Book event" class="btn btn-primary"/>
                }
            }
            else
            {

            }
        </form>
    </div>
</div>