Coordinare/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coordinare.Models
{
    public class Booking
    {
        public Booking(int bookingId, int eventId, int userId, bool specialSeat, bool inWaitingList, DateTime bookingDate )
        {
            Booking_ID = bookingId;
            Event_ID = eventId;
            User_ID = userId;
            Special_Seat = specialSeat;
            InWaitingList = inWaitingList;
            BookingDate = bookingDate;
        }

        public Booking(int eventId, int userId, bool specialSeat, bool inWaitingList, DateTime bookingDate)
        {
            Event_ID = eventId;
            User_ID = userId;
            Special_Seat = specialSeat;
            InWaitingList = inWaitingList;
            BookingDate = bookingDate;
        }
        public Booking()
        {
            
        }
        public int Booking_ID { get; set; }

        public int Event_ID { get; set; }

        public int User_ID { get; set; }

        public bool Special_Seat { get; set; }

        public bool InWaitingList { get; set; }

        public DateTime BookingDate { get; set; }

    }
}

Coordinare/Pages/Bookings/CreateBooking.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Coordinare.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;

namespace Coordinare.Pages.Bookings
{
    public class CreateBookingModel : PageModel
    {
        private IBookingCatalog _service;
        private IEventCatalog _eventService;
        private LoginService _LService;
        private IRoomCatalog _Rservice;
        [BindProperty] public Booking CurrentBooking { get; set; }
        public Event Event { get; set; }
        [BindProperty] public User User { get; set; }
        public CreateBookingModel(IBookingCatalog service, IEventCatalog eventService, LoginService lService, IRoomCatalog Rservice)
        {
            _service = service;
            _eventService = eventService;
            _LService = lService;
            _Rservice = Rservice;
        }
        public void OnGet(int EventID)
        {
            Event = _eventService.GetEventFromId(EventID).Result;
            User = _LService.GetLoggedInUser();
            CurrentBooking = new Booking();
            CurrentBooking.User_ID = User.User_ID;
            CurrentBooking.Event_ID = EventID;
            CurrentBooking.BookingDate = DateTime.Now;
            Event.Room_ID ??= null;
            if (!string.IsNullOrEmpty(Event.Room_ID) && _Rservice.GetRoomsFromIdAsync(Event.Room_ID).Result.Capacity - _service.GetBookingsFromEvent(EventID).Result.Count >= 0) 
            {
                CurrentBooking.InWaitingList = false;
            }
            else
            {
                CurrentBooking.InWaitingList = true;
            }

        }

        public async Task<IActionResult>OnPostBooking()
        {
            if (await _service.CreateBooking(CurrentBooking) == true)
            {
                return RedirectToPage("/Events/Index");
            }
            else
            {
                return Page();
            }
            
            
        }

        public async Task<IActionResult>OnPostReturn()
        {
            return  RedirectToPage("/Events/Index");
        }
    }
}

Coordinare/Pages/Bookings/EventBookings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Bookings
{
    public class EventBookingsModel : PageModel
    {
        public List<Booking> bookings { get; private set; }

        [BindProperty] public int eventID { get; set; }

        private IBookingCatalog bookingCatalog;

        public EventBookingsModel(IBookingCatalog bService)
        {
            this.bookingCatalog = bService;
        }
        public async Task OnGetAsync(int Event_ID)
        {
           bookings = bookingCatalog.GetBookingsFromEvent(Event_ID).Result;
        }
    }
}

Coordinare/Pages/Bookings/UserBookings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Bookings
{
    public class UserBookingsModel : PageModel
    {
        public List<Booking> bookings { get; private set; }

        [BindProperty] public int userID { get; set; }

        private IBookingCatalog bookingCatalog;

        public UserBookingsModel(IBookingCatalog bService)
        {
            this.bookingCatalog = bService;
        }
        public async Task OnGetAsync(int User_ID)
        {
            bookings = bookingCatalog.GetBookingsFromEvent(User_ID).Result;
        }
    }
}

Coordinare/Pages/Bookings/CreateBooking.cshtml
@page
@model Coordinare.Pages.Bookings.CreateBookingModel
@{
}

@{
    ViewData["Title"] = "Create Booking";
}

<h4 style="color:black"> Create Booking</h4>





<form method="post">
    <div class="form-group" >
        @if (Model.User.Specialaid)
        {
            <div>
                <label asp-for="@Model.CurrentBooking.Special_Seat">special seat?</label>
                <input type="checkbox" asp-for="@Model.CurrentBooking.Special_Seat"/>
            </div>
        }

    </div>
    <input type="hidden" asp-for="@Model.CurrentBooking.User_ID" />
    <input type="hidden" asp-for="@Model.CurrentBooking.Event_ID" />
    <input type="hidden" asp-for="@Model.CurrentBooking.InWaitingList" />
    <input type="hidden" asp-for="@Model.CurrentBooking.Special_Seat" />
    <input type="hidden" asp-for="@Model.CurrentBooking.BookingDate" />
    <input type="hidden" asp-for="@Model.User" />
    <div class="form-group">
        <button asp-page-handler="Return" class="btn-secondary" style="padding-right: 30px; float: left;background-color: red">back to event overview</button>&nbsp; | &nbsp;
        <button asp-page-handler="Booking" class="btn-primary">Confirm Booking</button>
    </div>
</form>

Coordinare/Pages/Bookings/EventBookings.cshtml
@page
@model Coordinare.Pages.Bookings.EventBookingsModel
@{
}

@{
    ViewData["Title"] = "EventBookings";
}





<h4 style="color:crimson"> List of bookings</h4>

<table class="table table-bordered">
    <thead class="thead-light">
    <tr>
        <th>
            booking ID
        </th>
        <th>
            Event ID
        </th>
        <th>
            User ID
        </th>
        <th>
            Special Seat
        </th>
        <th>
            In waiting list
        </th>
        <th>
            Booking date
        </th>

    </tr>
    </thead>
    <tbody>
    @if (Model.bookings.Count() != 0)
    {
        @foreach (var item in Model.bookings)
        {
            <tr>
                <td>
                    @item.Booking_ID
                </td>
                <td>
                    @item.Event_ID
                </td>
                <td>
                    @item.User_ID
                </td>
                <td>
                    @item.Special_Seat
                </td>
                <td>
                    @item.InWaitingList
                </td>
                <td>
                    @item.BookingDate
                </td>
            </tr>
        }
    }
</table>

Coordinare/Pages/Bookings/UserBookings.cshtml
@page
@model Coordinare.Pages.Bookings.UserBookingsModel
@{
}

<h4 style="color:crimson"> List of bookings</h4>

<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>
                booking ID
            </th>
            <th>
                Event ID
            </th>
            <th>
                User ID
            </th>
            <th>
                Special Seat
            </th>
            <th>
                In waiting list
            </th>
            <th>
                Booking date
            </th>

        </tr>
    </thead>
    <tbody>
        @if (Model.bookings.Count() != 0)
        {
            @foreach (var item in Model.bookings)
            {
                <tr>
                    <td>
                        @item.Booking_ID
                    </td>
                    <td>
                        @item.Event_ID
                    </td>
                    <td>
                        @item.User_ID
                    </td>
                    <td>
                        @item.Special_Seat
                    </td>
                    <td>
                        @item.InWaitingList
                    </td>
                    <td>
                        @item.BookingDate
                    </td>
                </tr>
            }
        }
</table>