Coordinare/Pages/Events/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Coordinare.Pages.Events
{
    public class CreateModel : PageModel
    {
        private IEventCatalog _eservice;
        private IRoomCatalog _rservice;
        private IUserCatalog _uservice;
        private ITagSelection _tservice;

        private Object _lock = new object();
        [BindProperty] public Event Event { get; set; }
        public string Time { get; set; }
        public List<TagName> Tags { get; set; }
        public List<Room> Rooms { get; set; }
        public List<User> Speakers { get; set; }

        [BindProperty]
        public TimeSpan dura { get; set; }
        public CreateModel(IEventCatalog eservice, IRoomCatalog rservice, IUserCatalog uservice, ITagSelection tservice)
        {
            _eservice = eservice;
            _rservice = rservice;
            _uservice = uservice;
            _tservice = tservice;
            Rooms = _rservice.GetAllRoomsAsync().Result;
            Speakers = uservice.GetAllUsersAsync().Result.FindAll(u => u.Speaker == true);
        }

        public void OnGet()
        {
            Tags = _tservice.GetTagNames().Result;
            Tags ??= new List<TagName>();
            Time = DateTime.Now.ToString("yyyy-MM-ddT00:00");
        }

        public async Task<IActionResult> OnPostAsync(int sid, List<int> tag)
        {

            Event place = new Event();
            Event.LastUpdated = DateTime.Now;
            Event.Speaker = _uservice.GetUserFromIdAsync(sid).Result;
            if (!ModelState.IsValid && Event.Speaker == null)
            {
                return Page();
            }

            if (_eservice.GetAllEvents().Result.Exists(e => !(e.Room_ID == Event.Room_ID && ((Event.DateTime.Add(Event.Duration) < e.DateTime) || (Event.DateTime > e.DateTime.Add(e.Duration))))))
            {
                lock (_lock)
                {
                    _eservice.CreateEvent(Event);
                    List<Event> el = _eservice.GetAllEvents().Result;
                    place = el.Last();
                }
                foreach (int item in tag)
                {
                    _tservice.CreateNewTagToEvent(place, _tservice.GetTagNameFromId(item).Result);
                }
            }
            return RedirectToPage("GetAllEvents");

        }

    }
}

Coordinare/Pages/Events/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace Coordinare.Pages.Events
{
    public class DeleteModel : PageModel
    {
        private IEventCatalog _service;
        private IUserCatalog _uservice;
        public Event Event { get; set; }
        public User Speaker { get; set; }
        public DeleteModel(IEventCatalog service, IUserCatalog uservice)
        {
            _service = service;
            _uservice = uservice;
        }
        public void OnGet(int id)
        {
          //  Func<int, bool> testbool = i => i == 0 ? true : false;
          Event = _service.GetEventFromId(id).Result;
          Speaker = _uservice.GetUserFromIdAsync(Event.Speaker.User_ID).Result;

        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            _service.DeleteEvent(id);
            return RedirectToPage("GetAllEvents");
        }
    }
}

Coordinare/Pages/Events/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Coordinare.Interfaces;
using Coordinare.Models;

namespace Coordinare.Pages.Events
{
    public class UpdateModel : PageModel
    {
        private IEventCatalog _service;
        private IRoomCatalog _rservice;
        private IUserCatalog _uservice;
        [BindProperty]
        public Event Event { get; set; }
        public List<Room> Rooms { get; set; }
        public List<User> Speakers { get; set; }
        public string Time { get; set; }
        public UpdateModel(IEventCatalog service, IRoomCatalog rservice, IUserCatalog uservice)
        {
            _service = service;
            _rservice = rservice;
            _uservice = uservice;
            Rooms = _rservice.GetAllRoomsAsync().Result;
            Speakers = uservice.GetAllUsersAsync().Result.FindAll(u => u.Speaker == true);
        }
        public async void OnGet(int id)
        {
          Event = await _service.GetEventFromId(id);
          Time = DateTime.Now.ToString("yyyy-MM-ddT00:00");
        }
        public async Task<IActionResult> OnPostAsync(int sid)
        {
            Event.Speaker = _uservice.GetUserFromIdAsync(sid).Result;
            Event.LastUpdated = DateTime.Now;
            if (!ModelState.IsValid && Event.Speaker == null)
            {
                return Page();
            }
            _service.UpdateEvent(Event, Event.Event_ID);
            return RedirectToPage("GetAllEvents");
            
        }
    }
}

Coordinare/Pages/Rooms/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Rooms
{
    public class DeleteModel : PageModel
    {
        private IRoomCatalog _service;
        [BindProperty] public Room Room { get; set; }
        public string TextBox { get; set; }

        public DeleteModel(IRoomCatalog service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            TextBox = "Are you sure that you want to delete?";
            Room = await _service.GetRoomsFromIdAsync(id);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        { 
            await _service.DeleteRoomAsync(Room.Room_ID);
            return RedirectToPage("GetAllRooms");
        }
    }
}

Coordinare/Pages/Rooms/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Exceptions;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Rooms
{
    public class UpdateModel : PageModel
    {

        private IRoomCatalog _service;
        [BindProperty] 
        public Room Room { get; set; }
        public string TextBox { get; set; }
        [BindProperty] 
        public string OldId { get; set; }
        //public List<Room> Rooms { get; set; }

        public UpdateModel(IRoomCatalog service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            OldId = id;
            TextBox = "Update a Room?";
            Room = await _service.GetRoomsFromIdAsync(id);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Room room)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            try
            {
                await _service.UpdateRoomAsync(Room, OldId);
            }
            catch (ExistsException e)
            {
                TextBox = $"Error! {e.Message}";
                return Page();
            }
            return RedirectToPage("GetAllRooms");
        }
    }
}

Coordinare/Pages/Users/ChangePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Coordinare.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Users
{
    public class ChangePasswordModel : PageModel
    {
        private IUserCatalog userCatalog;
        public LoginService logService;
        private string _newPassword;
        public string AccessDenied = "";

        public ChangePasswordModel(IUserCatalog userCatalog, LoginService logService)
        {
            this.userCatalog = userCatalog;
            this.logService = logService;
        }

        [BindProperty]
        public new User User { get; set; }

        public IActionResult OnPost(int? id)
        {
            if (userCatalog.GetUserFromIdAsync((int)id).Result.Password == User.PasswordCheck)
            {
                _newPassword = User.Password;
                User = userCatalog.GetUserFromIdAsync((int)id).Result;
                User.Password = _newPassword;

                userCatalog.UpdateUserAsync(User, (int)id);
                return RedirectToPage("/Users/Details", new { id = id });
            }

            AccessDenied = "Wrong password";
            return Page();
        }
    }
}

Coordinare/Pages/Users/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Exceptions;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Users
{
    public class DeleteModel : PageModel
    {
        private readonly IUserCatalog userCatalog;
        [BindProperty] public User User { get; set; }
        public string InfoText { get; set; }

        public DeleteModel(IUserCatalog userCatalog)
        {
            this.userCatalog = userCatalog;
        }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            InfoText = "You are deleting a user! Be sure.";
            User = await userCatalog.GetUserFromIdAsync(id);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                await userCatalog.DeleteUserAsync(User.User_ID);
                
            }
            catch (Exception e)
            {
                InfoText = $"Something went wrong! {e.Message}";
                return Page();
            }
            return RedirectToPage("GetAllUsers");
        }
    }
}

Coordinare/Pages/Users/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Users
{
    public class DetailsModel : PageModel
    {
        private IUserCatalog userCatalog;
        
        [BindProperty] public new User User { get; set; }

        public DetailsModel(IUserCatalog userCatalog)
        {
            this.userCatalog = userCatalog;
        }
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
                return NotFound();

            User = await userCatalog.GetUserFromIdAsync((int)id);

            if (User == null)
                return NotFound();

            return Page();
        }

        public IActionResult OnPostUpdateUser(int id)
        {
            return RedirectToPage("/Users/Update", new { id = id });
        }
        public IActionResult OnPostChangePassword(int id)
        {
            return RedirectToPage("/Users/ChangePassword", new { id = id });
        }
        public IActionResult OnPostDeleteUser(int id)
        {
            return RedirectToPage("/Users/Delete", new { id = id });
        }
    }
}

Coordinare/Pages/Users/GetAllUsers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Users
{
    public class GetAllUsersModel : PageModel
    {
        public List<User> Users { get; private set; }

        private IUserCatalog userCatalog;

        public GetAllUsersModel(IUserCatalog userCatalog)
        {
            this.userCatalog = userCatalog;
        }

        public async Task OnGetAsync()
        {
            Users = /*await*/ userCatalog.GetAllUsersAsync().Result;
        }
        public IActionResult OnPostCreateUser()
        {
            return RedirectToPage("/Users/Create");
        }
    }
}

Coordinare/Pages/Users/Log/LogIn.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Coordinare.Interfaces;
using Coordinare.Models;
using Coordinare.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Users.Log
{
    public class LogInModel : PageModel
    {
        private readonly IUserCatalog catalog;
        private readonly LoginService loginService;
        public string AccessDenied = "";

        public LogInModel(IUserCatalog catalog, LoginService loginService)
        {
            this.catalog = catalog;
            this.loginService = loginService;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public new User User { get; set; }

        public IActionResult OnPost()
        {
            foreach (User user in catalog.GetAllUsersAsync().Result)
            {
                if (user.Username == User.Username)
                {
                    if (user.Password == User.PasswordCheck)
                    {
                        TempData["Username"] = User.Username;

                        Response.Cookies.Append("UserId", $"{user.User_ID}");
                        loginService.UserLogin(user);
                        return RedirectToPage("/Index");
                    }
                }

                AccessDenied = "Username/Password doesn't exist";
            }

            return Page();
        }
    }
}

Coordinare/Pages/Users/Log/LogOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Users.Log
{
    public class LogOutModel : PageModel
    {
        private readonly LoginService logInService;

        public LogOutModel(LoginService logInService)
        {
            this.logInService = logInService;
        }

        public IActionResult OnGet()
        {
            logInService.UserLogout();
            Response.Cookies.Delete("UserId");

            return RedirectToPage("/Index");
        }
    }
}

Coordinare/Pages/Users/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coordinare.Exceptions;
using Coordinare.Interfaces;
using Coordinare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Coordinare.Pages.Users
{
    public class UpdateModel : PageModel
    {
        private readonly IUserCatalog userCatalog;
        [BindProperty(SupportsGet = true)] public User User { get; set; }
        public string InfoText { get; set; }
        public List<User> Users { get; private set; }

        public UpdateModel(IUserCatalog userCatalog)
        {
            this.userCatalog = userCatalog;
        }

        public async Task OnGetAsync(int id)
        {
            InfoText = "Enter new information";
            User = await userCatalog.GetUserFromIdAsync(id);
            Users = await userCatalog.GetAllUsersAsync();
        }

        public async Task<IActionResult> OnPostAsync(User user)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            try
            {
                await userCatalog.UpdateUserAsync(user, user.User_ID);
                Users = await userCatalog.GetAllUsersAsync();
            }
            catch (ExistsException e)
            {
                InfoText = $"Something went wrong! {e.Message}";
                return Page();
            }
            return RedirectToPage("GetAllUsers");
        }
    }
}

Coordinare/Pages/Users/ChangePassword.cshtml
@page
@using Coordinare.Services
@model Coordinare.Pages.Users.ChangePasswordModel
@{
    ViewData["Title"] = "Change password";
}

<h1>Change password</h1>

<hr />
<p class="text-danger">@Model.AccessDenied</p>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="User.User_ID" />
            <div class="form-group">
                <label asp-for="User.PasswordCheck" class="control-label">Write password for safety</label>
                <input asp-for="User.PasswordCheck" class="form-control" />
                <span asp-validation-for="User.PasswordCheck" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Password" class="control-label"></label>
                <input asp-for="User.Password" class="form-control" />
                <span asp-validation-for="User.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Password2" class="control-label"></label>
                <input asp-for="User.Password2" class="form-control" />
                <span asp-validation-for="User.Password2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Gem ændringer" class="btn button btn-dark" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="/Users/Details" asp-route-id="@Model.logService.GetLoggedInUser().User_ID">Tilbage til oversigt</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Coordinare/Pages/Users/Create.cshtml
@page
@model Coordinare.Pages.Users.CreateModel
@{
    ViewData["Title"] = "Create user";
}


<h3>Create user</h3>
<hr />
<div class="alert alert-warning" role="alert">
    @Model.InfoText
</div>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.User.Name" class="control-label"></label>
                <input asp-for="@Model.User.Name" class="form-control" />
                <span asp-validation-for="@Model.User.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Username" class="control-label"></label>
                <input asp-for="@Model.User.Username" class="form-control" />
                <span asp-validation-for="@Model.User.Username" class="text-danger"></span>
            </div>
            @*Autogenereret password!!*@
            <div class="form-group">
                <label asp-for="@Model.User.Password" class="control-label"></label>
                <input readonly="readonly" asp-for="@Model.User.Password" class="form-control" value="@Model.RndPass" />
                @*<span asp-validation-for="User.Password" class="text-danger"></span>*@
            </div>

            <div class="form-group">
                <label asp-for="@Model.User.Password2" class="control-label"></label>
                <input asp-for="@Model.User.Password2" class="form-control" />
                <span asp-validation-for="User.Password2" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.User.Phone" class="control-label"></label>
                <input asp-for="@Model.User.Phone" class="form-control" />

            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Email" class="control-label"></label>
                <input asp-for="@Model.User.Email" class="form-control" />
                <span asp-validation-for="@Model.User.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Speaker" class="control-label"></label>
                <input type="radio" asp-for="@Model.User.Speaker" value="true" />Yes
                <input type="radio" asp-for="@Model.User.Speaker" value="false" />No
                <span asp-validation-for="@Model.User.Speaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Specialaid" class="control-label"></label>
                <input type="radio" asp-for="@Model.User.Specialaid" value="true" />Yes
                <input type="radio" asp-for="@Model.User.Specialaid" value="false" />No
                <span asp-validation-for="@Model.User.Specialaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Admin" class="control-label"></label>
                <input type="radio" asp-for="@Model.User.Admin" value="true" />Yes
                <input type="radio" asp-for="@Model.User.Admin" value="false" />No
                <span asp-validation-for="@Model.User.Specialaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark" />&nbsp; | &nbsp;
                <a asp-page="./GetAllUsers">Back to the overview</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Coordinare/Pages/Users/Details.cshtml
@page
@model Coordinare.Pages.Users.DetailsModel
@{
    ViewData["Title"] = "Profile";
}

<style>
    th {
        background-color: #e9ecef;
    }
    label{
        font-weight: bold;
    }
    .table{
        width: 50%;
    }
    .form-group{
        border: groove;
        padding: 10px;
    }
</style>

<table class="table table-bordered">
    <tr>
        <th>
            <label asp-for="User.Name" class="control-label"></label>
        </th>
        <td>
            @Model.User.Name
        </td>
    </tr>
    <tr>
        <th>
            <label asp-for="User.Username" class="control-label"></label>
        </th>

        <td>
            @Model.User.Username
        </td>
    </tr>
    <tr>
        <th>
            <label asp-for="User.Password" class="control-label"></label>
        </th>

        <td>
            @Model.User.Password
        </td>
    </tr>
    <tr>
        <th>
            <label asp-for="User.Phone" class="control-label"></label>
        </th>

        <td>
            @Model.User.Phone
        </td>
    </tr>
    <tr>
        <th>
            <label asp-for="User.Email" class="control-label"></label>
        </th>
        <td>
            @Model.User.Email
        </td>
    </tr>
</table>

<div class="form-group" style="width: 200px">
    <label asp-for="@Model.User.Speaker" class="control-label"></label>
    @if (Model.User.Speaker)
    {
        <div style="display: block; margin-left: auto; margin-right: auto; width: 50%;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z" />
                <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z" />
            </svg>
        </div>
    }
    else
    {
        <div style="display: block; margin-left: auto; margin-right: auto; width: 50%;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
            </svg>
        </div>
    }
</div>
<div class="form-group" style="width: 200px">
    <label asp-for="@Model.User.Specialaid" class="control-label"></label>
    @if (Model.User.Specialaid)
    {
        <div style="display: block; margin-left: auto; margin-right: auto; width: 50%;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z" />
                <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z" />
            </svg>
        </div>
    }
    else
    {
        <div style="display: block; margin-left: auto; margin-right: auto; width: 50%;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
            </svg>
        </div>
    }
</div>

<form method="post" asp-page-handler="UpdateUser">
    <p>
        <button class="alert-info">Update information</button>
    </p>
    <input type="hidden" name="id" value="@Model.User.User_ID" />
</form>
<form method="post" asp-page-handler="ChangePassword">
    <p>
        <button class="alert-info">Change password</button>
    </p>
    <input type="hidden" name="id" value="@Model.User.User_ID" />
</form>
<form method="post" asp-page-handler="DeleteUser">
    <p>
        <button class="alert-danger">Delete user</button>
    </p>
    <input type="hidden" name="id" value="@Model.User.User_ID" />
</form>